# Generated by Django 5.0.4 on 2024-08-27 22:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
