# Generated by Django 5.0.4 on 2024-08-28 01:58

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0002_alter_contact_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="Phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region="NG"
            ),
        ),
    ]
